/**
 * Generates the flag stylesheets from `flags/svg/`.
 *
 * The assets ship from the package root rather than `dist/`, because Sass and
 * CSS tooling resolve paths on the filesystem and ignore the `exports` map.
 * Publishing them at `flags/` makes the documented import path the real one.
 *
 * The SVGs are never modified. See docs/FLAGS.md for why they are not minified.
 */
import {
  readdirSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  statSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validate } from './validate-data.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'flags', 'svg');
const OUT = join(ROOT, 'flags');

// The flags are drawn 4:3.
const WIDTH = 40;
const HEIGHT = 30;

const codes = readdirSync(SRC)
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.replace(/\.svg$/, '').toLowerCase())
  .sort();

if (codes.length === 0) throw new Error('[build-flags] no SVGs found in flags/svg');

validate();

const BANNER = 'Generated by scripts/build-flags.mjs from flags/svg/. Do not edit.';

function css() {
  const base = `.flag {
  position: relative;
  display: inline-block;
  background-size: cover;
  background-repeat: no-repeat;
  /* width:height aspect ratio of flag images is 4:3 */
  width: ${WIDTH}px;
  height: ${HEIGHT}px;
}`;
  const rules = codes
    .map((c) => `.flag-${c} {\n  background-image: url('../svg/${c}.svg');\n}`)
    .join('\n\n');
  return `/* ${BANNER} */\n${base}\n\n${rules}\n`;
}

function minCss() {
  const base =
    '.flag{position:relative;display:inline-block;background-size:cover;' +
    `background-repeat:no-repeat;width:${WIDTH}px;height:${HEIGHT}px}`;
  const rules = codes.map((c) => `.flag-${c}{background-image:url(../svg/${c}.svg)}`).join('');
  return `/* ${BANNER} */\n${base}${rules}\n`;
}

function scss() {
  // URLs are written literally, not built with #{$var} interpolation: no bundler
  // or Sass compiler can statically rebase an interpolated url(), so the SVGs
  // would never be resolved or emitted.
  const rules = codes
    .map((c) => `.flag-${c} {\n  background-image: url('../svg/${c}.svg');\n}`)
    .join('\n\n');
  return `// ${BANNER}

$flag-width: ${WIDTH}px !default;
$flag-height: ${HEIGHT}px !default;

.flag {
  position: relative;
  display: inline-block;
  background-size: cover;
  background-repeat: no-repeat;
  width: $flag-width;
  height: $flag-height;
}

${rules}
`;
}

rmSync(join(OUT, 'css'), { recursive: true, force: true });
rmSync(join(OUT, 'scss'), { recursive: true, force: true });
mkdirSync(join(OUT, 'css'), { recursive: true });
mkdirSync(join(OUT, 'scss'), { recursive: true });

writeFileSync(join(OUT, 'css', 'flags.css'), css(), 'utf8');
writeFileSync(join(OUT, 'css', 'flags.min.css'), minCss(), 'utf8');
writeFileSync(join(OUT, 'scss', 'flags.scss'), scss(), 'utf8');

const svgBytes = readdirSync(SRC).reduce((n, f) => n + statSync(join(SRC, f)).size, 0);
const kb = (n) => `${(n / 1000).toFixed(0)} KB`;

console.log(`flags: ${codes.length} SVGs published unmodified (${kb(svgBytes)})`);
console.log(
  `  stylesheets generated: flags.css ${kb(Buffer.byteLength(css()))}, ` +
    `flags.min.css ${kb(Buffer.byteLength(minCss()))}, flags.scss ${kb(Buffer.byteLength(scss()))}`
);
